import type { Metadata, Viewport } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import dynamic from "next/dynamic";
import JsonLd from "@/components/JsonLd";
import "./globals.css";

const DynamicScrollToTop = dynamic(() => import("@/components/ScrollToTop"));

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["vietnamese"],
  display: "swap",
  variable: "--font-plus-jakarta",
});

const SITE_URL = "https://tranhuyland.vn";
const SITE_NAME = "Trần Huy Land";
const DEFAULT_OG_IMAGE = `${SITE_URL}/og-image.jpg`;

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: "#ffffff",
};

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),

  title: {
    default: "Trần Huy Land | Kho Nhà Đất Chính Chủ Hải Châu Cẩm Lệ Đà Nẵng",
    template: "%s | Trần Huy Land",
  },

  description:
    "Mua bán, ký gửi nhà đất chính chủ uy tín tại Hải Châu, Cẩm Lệ, Đà Nẵng. Cập nhật giỏ hàng thực tế mỗi ngày, pháp lý minh bạch.",

  keywords: [
    "nhà đất đà nẵng",
    "nhà đất chính chủ hải châu",
    "ký gửi nhà đất cẩm lệ",
    "nhà đất trần huy",
    "mua nhà đà nẵng",
    "bán đất cẩm lệ",
  ],

  alternates: {
    canonical: SITE_URL,
  },

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },

  icons: {
    icon: "/icon.png",
    shortcut: "/icon.png",
    apple: "/apple-touch-icon.png",
  },

  openGraph: {
    type: "website",
    locale: "vi_VN",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: "Trần Huy Land | Kho Nhà Đất Chính Chủ Hải Châu Cẩm Lệ Đà Nẵng",
    description:
      "Mua bán, ký gửi nhà đất chính chủ uy tín tại Đà Nẵng. Cập nhật nhà đất thực tế mỗi ngày.",
    images: [
      {
        url: DEFAULT_OG_IMAGE,
        width: 1200,
        height: 630,
        alt: SITE_NAME,
      },
    ],
  },

  twitter: {
    card: "summary_large_image",
    title: "Trần Huy Land | Kho Nhà Đất Chính Chủ Đà Nẵng",
    description:
      "Kho nhà đất chính chủ Đà Nẵng cập nhật mỗi ngày.",
    images: [DEFAULT_OG_IMAGE],
    site: "@tranhuyland",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="vi"
      className={plusJakartaSans.variable}
      suppressHydrationWarning
    >
      <head>
        {/* 🚀 Chặn trình duyệt tự khôi phục vị trí cuộn */}
        <script
          dangerouslySetInnerHTML={{
            __html: `history.scrollRestoration = 'manual'`,
          }}
        />

        {/* Preload critical fonts for LCP text */}
        {/* Font hashes are auto-generated by Next.js; preload via link tags would break on rebuild */}

        {/* Preconnect to image CDNs to reduce connection latency */}
        <link rel="preconnect" href="https://res.cloudinary.com" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="https://res.cloudinary.com" />
        <link rel="preconnect" href="https://i.postimg.cc" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="https://i.postimg.cc" />
        <link rel="dns-prefetch" href="https://lh3.googleusercontent.com" />
        <link rel="dns-prefetch" href="https://images.unsplash.com" />
      </head>

      <body
        className={`${plusJakartaSans.className} antialiased min-h-screen flex flex-col pb-20 md:pb-0 bg-slate-50`}
        suppressHydrationWarning
      >
        <JsonLd />
        {children}
        <DynamicScrollToTop />
      </body>
    </html>
  );
}
